# Generated by Django 6.0.2 on 2026-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bgp_asn',
            field=models.PositiveIntegerField(blank=True, help_text='BGP Autonomous System Number', null=True),
        ),
    ]
