# Generated by Django 6.0.2 on 2026-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_bgp_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='device_brand',
            field=models.CharField(blank=True, choices=[('palo_alto', 'Palo Alto'), ('cisco', 'Cisco'), ('fortinet', 'Fortinet'), ('juniper', 'Juniper'), ('check_point', 'Check Point'), ('other', 'Other')], help_text='Firewall/device brand', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='device_group',
            field=models.CharField(blank=True, help_text='Device group in management platform', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='management_platform',
            field=models.CharField(blank=True, help_text='Management platform name, e.g. Panorama', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='management_type',
            field=models.CharField(blank=True, choices=[('centralized', 'Centrally Managed'), ('standalone', 'Standalone')], help_text='Centrally managed or standalone', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='template_name',
            field=models.CharField(blank=True, help_text='Template/template stack in management platform', max_length=100),
        ),
    ]
