# Generated by Django 6.0.2 on 2026-02-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_device_brand_site_device_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('requester', 'Requester'), ('infosec', 'InfoSec Approver'), ('network', 'Network Approver'), ('deployer', 'Deployer'), ('admin', 'Administrator')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
