# Generated by Django 6.0.2 on 2026-02-06 19:59

from django.db import migrations


ALL_ROLES = ["requester", "infosec", "network", "deployer", "admin"]


def assign_all_roles_to_superusers(apps, schema_editor):
    User = apps.get_model("core", "User")
    UserRole = apps.get_model("core", "UserRole")
    for user in User.objects.filter(is_superuser=True):
        for role in ALL_ROLES:
            UserRole.objects.get_or_create(user=user, role=role)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_multi_role"),
    ]

    operations = [
        migrations.RunPython(
            assign_all_roles_to_superusers,
            migrations.RunPython.noop,
        ),
    ]
