# Generated by Django 6.0.2 on 2026-02-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assign_roles_to_superusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tunnel_interface_end',
            field=models.PositiveIntegerField(blank=True, help_text='End of tunnel interface number range (e.g. 199)', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='tunnel_interface_start',
            field=models.PositiveIntegerField(blank=True, help_text='Start of tunnel interface number range (e.g. 100)', null=True),
        ),
        migrations.CreateModel(
            name='TunnelAddressPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='Parent CIDR from which /30 subnets are carved, e.g. 10.255.0.0/24', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnel_address_pools', to='core.site')),
            ],
            options={
                'ordering': ['site', 'cidr'],
                'unique_together': {('site', 'cidr')},
            },
        ),
    ]
