# Generated by Django 6.0.2 on 2026-06-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_tunnel_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Vendor → Us)'), ('outbound', 'Outbound (We → Vendor)')], help_text='Whether this pool NATs inbound (vendor→us) or outbound (us→vendor) traffic', max_length=10)),
                ('cidr', models.CharField(help_text='Dedicated NAT range, e.g. 10.111.96.0/24 (outbound) or 10.111.100.0/24 (inbound)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_pools', to='core.site')),
            ],
            options={
                'ordering': ['site', 'direction', 'cidr'],
                'unique_together': {('site', 'direction', 'cidr')},
            },
        ),
    ]
