# Generated by Django 6.0.2 on 2026-06-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_natpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='natpool',
            name='scope',
            field=models.CharField(choices=[('site', 'Site-specific'), ('shared', 'Shared (DR pair)')], default='site', help_text='Site-specific (single-site requests) or shared (DR-pair requests)', max_length=10),
        ),
        migrations.AlterField(
            model_name='natpool',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Owning site for site-specific pools; empty for shared (DR) pools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_pools', to='core.site'),
        ),
    ]
