# Generated by Django 6.0.2 on 2026-06-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_natpool_scope_alter_natpool_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'East Coast DR pair'", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_site', models.OneToOneField(help_text='Preferred site — advertised without AS-path prepend', on_delete=django.db.models.deletion.PROTECT, related_name='dr_peer_as_primary', to='core.site')),
                ('secondary_site', models.OneToOneField(help_text='Failover site — advertises the same NAT ranges with AS-path prepend', on_delete=django.db.models.deletion.PROTECT, related_name='dr_peer_as_secondary', to='core.site')),
            ],
            options={
                'verbose_name': 'DR peer',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='natpool',
            name='dr_peer',
            field=models.ForeignKey(blank=True, help_text='Owning DR peer for shared pools; empty for site-specific pools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_pools', to='core.drpeer'),
        ),
    ]
