# Generated by Django 6.0.2 on 2026-02-05 05:27

import apps.vpn.models.flow
import apps.vpn.models.request
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distribution_list_email', models.EmailField(blank=True, max_length=254)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('technical', 'Technical'), ('support', 'Support')], default='technical', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vpn.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VpnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=apps.vpn.models.request.generate_reference_number, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('purpose', models.TextField(blank=True)),
                ('directionality', models.CharField(blank=True, choices=[('consume', 'Consume (inbound)'), ('provide', 'Provide (outbound)'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('data_description', models.TextField(blank=True)),
                ('data_classification', models.CharField(blank=True, max_length=50)),
                ('vendor_endpoints_count', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('topology_type', models.CharField(blank=True, choices=[('bow_tie', 'Bow Tie'), ('matched_pairs', 'Matched Pairs'), ('any_to_any', 'Any to Any')], max_length=20)),
                ('vendor_endpoint_1_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vendor_endpoint_2_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ike_version', models.CharField(choices=[('1', 'IKEv1'), ('2', 'IKEv2')], default='2', max_length=2)),
                ('auth_method', models.CharField(choices=[('psk', 'Pre-Shared Key'), ('certificate', 'Certificate')], default='psk', max_length=20)),
                ('ike_encryption', models.CharField(blank=True, help_text='e.g. aes-256-cbc', max_length=50)),
                ('ike_integrity', models.CharField(blank=True, help_text='e.g. sha256', max_length=50)),
                ('ike_dh_group', models.CharField(blank=True, help_text='e.g. 14, 19, 20', max_length=20)),
                ('ike_lifetime', models.PositiveIntegerField(blank=True, help_text='Lifetime in seconds', null=True)),
                ('dpd_enabled', models.BooleanField(default=True)),
                ('ipsec_encryption', models.CharField(blank=True, help_text='e.g. aes-256-gcm', max_length=50)),
                ('ipsec_integrity', models.CharField(blank=True, help_text='e.g. sha256', max_length=50)),
                ('ipsec_pfs_group', models.CharField(blank=True, help_text='PFS DH group', max_length=20)),
                ('ipsec_lifetime', models.PositiveIntegerField(blank=True, help_text='Lifetime in seconds', null=True)),
                ('tunnel_mode', models.CharField(blank=True, default='tunnel', max_length=20)),
                ('routing_type', models.CharField(blank=True, choices=[('static', 'Static'), ('bgp', 'BGP')], max_length=10)),
                ('bgp_local_asn', models.PositiveIntegerField(blank=True, null=True)),
                ('bgp_remote_asn', models.PositiveIntegerField(blank=True, null=True)),
                ('bgp_peer_ip_local', models.GenericIPAddressField(blank=True, null=True)),
                ('bgp_peer_ip_remote', models.GenericIPAddressField(blank=True, null=True)),
                ('bgp_auth_enabled', models.BooleanField(default=False)),
                ('nat_supported', models.BooleanField(blank=True, null=True)),
                ('nat_exception_reason', models.TextField(blank=True)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('infosec_approved', 'InfoSec Approved'), ('infosec_changes_requested', 'InfoSec Changes Requested'), ('network_approved', 'Network Approved'), ('network_changes_requested', 'Network Changes Requested'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('deploy_ready', 'Deploy Ready'), ('deployed', 'Deployed'), ('active', 'Active'), ('recert_due', 'Recert Due'), ('recert_in_review', 'Recert In Review'), ('recert_approved', 'Recert Approved'), ('decommission_requested', 'Decommission Requested'), ('decommission_approved', 'Decommission Approved'), ('decommissioned', 'Decommissioned')], default='draft', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('our_endpoint_1_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_endpoint_1_requests', to='core.site')),
                ('our_endpoint_2_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_endpoint_2_requests', to='core.site')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_requests', to='vpn.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('source_cidr', models.CharField(max_length=50, validators=[apps.vpn.models.flow.validate_cidr])),
                ('destination_cidr', models.CharField(max_length=50, validators=[apps.vpn.models.flow.validate_cidr])),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', 'Any')], default='tcp', max_length=10)),
                ('destination_ports', models.CharField(blank=True, help_text='Comma-separated ports or ranges, e.g. 443,8443,10000-10100', max_length=200, validators=[apps.vpn.models.flow.validate_ports])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_flows', to='vpn.application')),
                ('vpn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='vpn.vpnrequest')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VpnRequestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.application')),
                ('vpn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.vpnrequest')),
            ],
            options={
                'unique_together': {('vpn_request', 'application')},
            },
        ),
        migrations.AddField(
            model_name='vpnrequest',
            name='applications',
            field=models.ManyToManyField(blank=True, through='vpn.VpnRequestApplication', to='vpn.application'),
        ),
    ]
