# Generated by Django 6.0.2 on 2026-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnrequest',
            name='vendor_cidrs',
            field=models.TextField(blank=True, help_text='Vendor CIDRs for static routing (one per line or comma-separated)'),
        ),
        migrations.AlterField(
            model_name='vpnrequest',
            name='directionality',
            field=models.CharField(blank=True, choices=[('we_initiate', 'We Initiate'), ('vendor_initiates', 'Vendor Initiates'), ('both', 'Both Can Initiate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vpnrequest',
            name='topology_type',
            field=models.CharField(blank=True, choices=[('bow_tie', 'Bow Tie'), ('matched_pairs', 'Matched Pairs')], max_length=20),
        ),
    ]
