# Generated by Django 6.0.2 on 2026-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_vpnrequest_vendor_cidrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnrequest',
            name='tunnel_ip_assignment',
            field=models.CharField(blank=True, choices=[('we_assign', 'We Assign (from tunnel IP pool)'), ('vendor_assigns', 'Vendor Assigns'), ('mutual', 'Mutually Agreed'), ('apipa', 'APIPA (169.254.x.x)')], default='', help_text='How tunnel interface IPs are assigned for BGP peering', max_length=20),
        ),
    ]
