# Generated by Django 6.0.2 on 2026-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_vpnrequest_tunnel_ip_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnrequest',
            name='bgp_remote_asn_2',
            field=models.PositiveIntegerField(blank=True, help_text='Vendor ASN for endpoint 2 (if different)', null=True),
        ),
        migrations.AlterField(
            model_name='vpnrequest',
            name='bgp_remote_asn',
            field=models.PositiveIntegerField(blank=True, help_text='Vendor ASN for endpoint 1', null=True),
        ),
    ]
