# Generated by Django 6.0.2 on 2026-02-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_vpnrequest_bgp_remote_asn_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficflow',
            name='direction',
        ),
    ]
