# Generated by Django 6.0.2 on 2026-02-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_remove_trafficflow_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('infosec', 'InfoSec'), ('network', 'Network')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_reviews', to=settings.AUTH_USER_MODEL)),
                ('vpn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='vpn.vpnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
