# Generated by Django 6.0.2 on 2026-02-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_tunnel_range'),
        ('vpn', '0006_approvalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnrequest',
            name='mutual_tunnel_ips',
            field=models.TextField(blank=True, default='', help_text='JSON: per-tunnel local/remote IPs when tunnel_ip_assignment is "mutual"'),
        ),
        migrations.AlterField(
            model_name='vpnrequest',
            name='tunnel_ip_assignment',
            field=models.CharField(blank=True, choices=[('we_assign', 'We Assign (from tunnel IP pool)'), ('mutual', 'Mutually Agreed'), ('apipa', 'APIPA (169.254.x.x)')], default='', help_text='How tunnel interface IPs are assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='TunnelInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunnel_number', models.PositiveIntegerField(help_text='Tunnel interface number assigned from site range')),
                ('local_ip', models.GenericIPAddressField(blank=True, help_text='Our side of the /30', null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, help_text='Vendor side of the /30', null=True)),
                ('subnet_cidr', models.CharField(blank=True, help_text='The /30 subnet, e.g. 10.255.0.0/30', max_length=50)),
                ('vendor_endpoint_ip', models.GenericIPAddressField(blank=True, help_text='Which vendor endpoint this tunnel connects to', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_pool', models.ForeignKey(blank=True, help_text='Source pool (null for APIPA/mutual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tunneladdresspool')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tunnel_interfaces', to='core.site')),
                ('vpn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnel_interfaces', to='vpn.vpnrequest')),
            ],
            options={
                'ordering': ['vpn_request', 'site', 'tunnel_number'],
                'unique_together': {('site', 'tunnel_number')},
            },
        ),
    ]
