# Generated by Django 6.0.2 on 2026-02-07 03:28

from django.db import migrations


def clear_vendor_assigns(apps, schema_editor):
    VpnRequest = apps.get_model("vpn", "VpnRequest")
    VpnRequest.objects.filter(tunnel_ip_assignment="vendor_assigns").update(
        tunnel_ip_assignment=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_tunnelinterface_and_mutual_ips'),
    ]

    operations = [
        migrations.RunPython(clear_vendor_assigns, migrations.RunPython.noop),
    ]
