# Generated by Django 6.0.2 on 2026-06-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_natpool'),
        ('vpn', '0008_clear_vendor_assigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Vendor → Us)'), ('outbound', 'Outbound (We → Vendor)')], help_text='Inbound (vendor→us) or outbound (us→vendor)', max_length=10)),
                ('nat_address', models.CharField(help_text="The NAT'd address/range carved from the pool, e.g. 10.111.96.10/32", max_length=50)),
                ('real_address', models.CharField(help_text='The real backend it translates to (vendor host for outbound, internal service for inbound)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nat_pool', models.ForeignKey(blank=True, help_text='Source pool this address was allocated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='core.natpool')),
                ('site', models.ForeignKey(help_text='The endpoint/firewall region where this NAT rule lives', on_delete=django.db.models.deletion.PROTECT, related_name='nat_mappings', to='core.site')),
                ('traffic_flow', models.ForeignKey(blank=True, help_text='The traffic flow this mapping serves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_mappings', to='vpn.trafficflow')),
                ('vpn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_mappings', to='vpn.vpnrequest')),
            ],
            options={
                'ordering': ['vpn_request', 'site', 'direction', 'nat_address'],
                'unique_together': {('site', 'direction', 'nat_address')},
            },
        ),
    ]
