# Generated by Django 6.0.2 on 2026-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_natmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficflow',
            name='direction',
            field=models.CharField(blank=True, choices=[('outbound', 'Outbound (We → Vendor)'), ('inbound', 'Inbound (Vendor → Us)')], default='', help_text="Who initiates this flow; blank falls back to the request's directionality", max_length=10),
        ),
    ]
