# Generated by Django 6.0.2 on 2026-06-10 22:40

from django.db import migrations, models


def backfill_stragglers(apps, schema_editor):
    """Catch any blank rows created between 0011 and this migration."""
    TrafficFlow = apps.get_model("vpn", "TrafficFlow")
    TrafficFlow.objects.filter(
        direction="", vpn_request__directionality="vendor_initiates"
    ).update(direction="inbound")
    TrafficFlow.objects.filter(direction="").update(direction="outbound")


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_backfill_flow_direction'),
    ]

    operations = [
        migrations.RunPython(backfill_stragglers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trafficflow',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound (We → Vendor)'), ('inbound', 'Inbound (Vendor → Us)')], default='outbound', help_text='Who initiates this flow — picks the boundary NAT pool (outbound vs inbound)', max_length=10),
        ),
    ]
